repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.6.0
    hooks:
      - id: pip-compile
        name: pip-compile setup.py
        args: 
          - --allow-unsafe
          - --generate-hashes
          - --reuse-hashes
        files: ^(setup\.py|requirements\.txt)$
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args: 
          - --allow-unsafe
          - --generate-hashes
          - --reuse-hashes
          - requirements-dev.in
        files: ^requirements-dev\.(in|txt)$
  - repo: https://github.com/PyCQA/pylint
    rev: v2.13.7
    hooks:
      - id: pylint
